/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f013x6.h"
#include "stm32_f103c6_gpio_driver.h"




void delay(int x)
{
	int i,j ;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}

}


void clock_init()
{

	RCC->APB2ENR |=(1<<2);
	RCC->APB2ENR |=(1<<3);
}


void GPIO_init()
{

  GPIO_CONFIGURATION pincnfg;

  //for PA1 as a floating input pin
  pincnfg.GPIO_PIN_MODE = GPIO_FLOATING_INPUT;
  pincnfg.GPIO_PIN_NUMBER =GPIO_PIN1;
  MCAL_GPIO_INIT(GPIOA, &pincnfg);

  //for PB1 as a push-pull output pin
  pincnfg.GPIO_PIN_MODE = GPIO_PUSHPULL_OUTPUT;
  pincnfg.GPIO_PIN_NUMBER= GPIO_PIN1;
  pincnfg.GPIO_OUTPUT_SPEED =GPIO_OUTPUT_10MHz;
  MCAL_GPIO_INIT(GPIOB, &pincnfg);



  //for PA6 as a floating input pin
  pincnfg.GPIO_PIN_MODE = GPIO_FLOATING_INPUT;
  pincnfg.GPIO_PIN_NUMBER =GPIO_PIN6;
  MCAL_GPIO_INIT(GPIOA, &pincnfg);

  //for PB12 as a push-pull output pin
  pincnfg.GPIO_PIN_MODE = GPIO_PUSHPULL_OUTPUT;
  pincnfg.GPIO_PIN_NUMBER= GPIO_PIN12;
  pincnfg.GPIO_OUTPUT_SPEED =GPIO_OUTPUT_10MHz;
  MCAL_GPIO_INIT(GPIOB, &pincnfg);



}

int main(void)
{
	clock_init();
	GPIO_init();


	while(1)
	{


	if( (MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN1)) ==0) //single press
	{
		MCAL_GPIO_TOGGLE(GPIOB,GPIO_PIN1);
		while((MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN1)) ==0);

	}

	if( (MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN6)) ==1) // single press
	{
		MCAL_GPIO_TOGGLE(GPIOB,GPIO_PIN12);

	}


		delay(1);

	}

	return 0;
}
