/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"
#include "EXTI.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t flag;
int control_register;
int IPSR_register,val;

void HardFault_Handler()
{

}


enum cpu_level{
	priviledged,
	unpriviledged
};


void cpu_access_level(enum cpu_level level)
{
	switch (level)
	{
	case  priviledged:

		__asm("MRS r3,CONTROL \n\t"
				" LSR r3,r3,#0x1 \n\t"
				"LSL r3,r3,#0x1 \n\t"
				"MSR CONTROL,r3");

		break;

	case unpriviledged:
		__asm("MRS r3,CONTROL \n\t"
				"ORR r3,r3,#0x1 \n\t"
				"MSR CONTROL,r3");
		break;

	}
}


void EXTI_irq()
{
	flag =1;

	cpu_access_level(priviledged);

}
int main(void)
{
		RCC_GPIOB_CLK_EN();
		RCC_AFIO_CLK_EN();


	EXTI_PinConfig_t EXTI_Config;


	EXTI_Config.EXTI_PIN =EXTI9PB9;
	EXTI_Config.IRQ_EN =EXTI_IRQ_Enable;
	EXTI_Config.Trigger_Case =EXTI_Trigger_RISING;
	EXTI_Config.P_IRQ_CallBack =EXTI_irq;
	MCAL_EXTI_GPIO_init(&EXTI_Config);

		cpu_access_level(unpriviledged);



	while(1)
	{
		if(flag)
		{
			flag=0;
		}
		else
		{

		}
	}
}
