/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "schedular.h"
#include "cortexM_os_porting.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
OS_task_ref Tref_1,Tref_2,Tref_3,Tref_4;
uint16_t task1_led,task2_led,task3_led,task4_led;


void task1()
{
	static int count;
	while(1){
		task1_led ^= 1;
		count++;
		if (count == 100) {
			MYRTOS_activate_task(&Tref_2);
		}
		if (count == 200) {
			count = 0;
		}

	}
}


void task2()
{
	static int count;

	while (1) {
		task2_led ^= 1;
		count++;

		if (count == 100) {
			MYRTOS_activate_task(&Tref_3);
		}
		if (count == 200) {
			count = 0;
			MYRTOS_terminate_task(&Tref_2);
		}

	}
}


void task3()
{
	static int count;

	while (1) {
		task3_led ^= 1;
		count++;

		if (count == 100) {
			MYRTOS_activate_task(&Tref_4);
		}
		if (count == 200) {
			count = 0;
			MYRTOS_terminate_task(&Tref_3);
		}

	}
}

void task4()
{
	static int count;

	while (1) {
		task4_led ^= 1;
		count++;


		if (count == 200) {
			count = 0;
			MYRTOS_terminate_task(&Tref_4);
		}

	}


}

int main(void)
{




	HAL_init();

	MYRTOS_init();





		Tref_1.priority =4;
		strcpy(Tref_1.task_name,"task1");
		Tref_1.task_stack_size=1024;
		Tref_1.p_task_function =task1;

		Tref_2.priority =3;
		strcpy(Tref_2.task_name,"task2");
		Tref_2.task_stack_size=1024;
		Tref_2.p_task_function =task2;

		Tref_3.priority =2;
		strcpy(Tref_3.task_name,"task3");
		Tref_3.task_stack_size=1024;
		Tref_3.p_task_function =task3;

		Tref_4.priority =1;
		strcpy(Tref_3.task_name,"task4");
		Tref_4.task_stack_size=1024;
		Tref_4.p_task_function =task4;


		MYRTOS_CreateTask(&Tref_1);
		MYRTOS_CreateTask(&Tref_2);
		MYRTOS_CreateTask(&Tref_3);
		MYRTOS_CreateTask(&Tref_4);


		MYRTOS_activate_task(&Tref_1);

		MYRTOS_start();




	while (1)
	{

	}
}
