/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32_f103c6_gpio_driver.h"
#include "stm32_f103c6_uart_driver.h"
#include "RCC_clock_configuration.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

unsigned short ch;
void clock_init();
void abdo_IRQ_callback();


int main(void)
{


	clock_init();

	UART_config Cnfg;
	Cnfg.uart_mode = uart_mode_TX_RX;
	Cnfg.uart_baudrate = uart_baud_115200;
	Cnfg.uart_IRQ_enable = uart_irq_enable_RXNE;
	Cnfg.uart_parity = uart_parity_none;
	Cnfg.uart_stopbits = stopbit_1;
	Cnfg.uart_payload_length = uart_payload_8bit;
	Cnfg.flow_ctrl = uart_flowctrl_none;
	Cnfg.P_IRQ_callback = abdo_IRQ_callback;

	MCAL_uart_init(UART1,&Cnfg );
	MCAL_GPIO_uart_init(UART1);


    while(1)
    {
//    	MCAL_uart_recieve(UART1,&ch , polling_disable);
//   	MCAL_uart_send(UART1,&ch , polling_enable);

    }


}



void abdo_IRQ_callback(){
	MCAL_uart_recieve(UART1,&ch , polling_disable);
	MCAL_uart_send(UART1,&ch , polling_enable);


}
void clock_init()
{

	RCC_GPIOA_CLOCK_ENABLE;
	RCC_GPIOB_CLOCK_ENABLE;
	RCC_AFIO_ENABLE;

}
