/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define  GPIOA_BASE 0x40010800
#define  GPIOA_CRH *(volatile unsigned int *)(GPIOA_BASE+0x04)
#define  GPIOA_ODR *(volatile unsigned int *)(GPIOA_BASE+0x0C)

//defining the RCC register base address
#define RCC_BASE 0x40021000
//APB2 clock enable register
#define RCC_APB2ENR *(volatile unsigned int *)(RCC_BASE + 0x18)

//APB1 clock enable register
#define RCC_APB1ENR *(volatile unsigned int *)(RCC_BASE +0x1C)

//clock configuration register for APB2 to divide
#define  RCC_CFGR  *(volatile unsigned int *)(RCC_BASE +0x04)

//enabling pll
#define RCC_CR *(volatile unsigned int *)(RCC_BASE +0x0)

int main(void)
{
//
//	Bits 21:18 PLLMUL[3:0]: PLL multiplication factor
//	These bits are written by software to define the PLL multiplication factor. They can be written only
//	when PLL is disabled.
//	000x: Reserved
//	0010: PLL input clock x 4
//	0011: PLL input clock x 5
//	0100: PLL input clock x 6
//	0101: PLL input clock x 7
//	0110: PLL input clock x 8
//	0111: PLL input clock x 9
//	10xx: Reserved
//	1100: Reserved
//	1101: PLL input clock x 6.5
//	111x: Reserved

	RCC_CFGR |= 0b0110<<18;


//===================================================================



//	Bits 1:0 SW[1:0]: System clock Switch
//Set and cleared by software to select SYSCLK source.
//Set by hardware to force HSI selection when leaving Stop and Standby mode or in case of failure of
//the HSE oscillator used directly or indirectly as system clock (if the Clock Security System is
//enabled).
//00: HSI selected as system clock
//01: HSE selected as system clock
//10: PLL selected as system clock
//11: Not allowed

	RCC_CFGR |= 0b10<<0;


//=========================================================



//	Bit 24 PLLON: PLL enable
//	Set and cleared by software to enable PLL.
//	Cleared by hardware when entering Stop or Standby mode. This bit can not be reset if the
//	PLL clock is used as system clock or is selected to become the system clock. Software
//	must disable the USB OTG FS clock before clearing this bit.
//	0: PLL OFF
//	1: PLL ON

	RCC_CR |= 1<<24;







//====================================================================


//	Bits 13:11 PPRE2[2:0]: APB high-speed prescaler (APB2)
//	Set and cleared by software to control the division factor of the APB High speed clock (PCLK2).
//	0xx: HCLK not divided
//	100: HCLK divided by 2
//	101: HCLK divided by 4
//	110: HCLK divided by 8
//	111: HCLK divided by 16

	RCC_CFGR |=(0b101<<11);


//==================================================================

//	Bits 10:8 PPRE1[2:0]: APB Low-speed prescaler (APB1)
//	Set and cleared by software to control the division factor of the APB Low speed clock (PCLK1).
//	0xx: HCLK not divided
//	100: HCLK divided by 2
//	101: HCLK divided by 4
//	110: HCLK divided by 8
//	111: HCLK divided by 16

	RCC_CFGR |=0b100<<8;



	//==================================================================

//	Bit 2 IOPAEN: I/O port A clock enable
//	Set and cleared by software.
//	0: I/O port A clock disabled
//	1:I/O port A clock enable
//now enabling clock for GPIOA

	RCC_APB2ENR |=1<<2;

// initializing GPIO
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	while(1)
	{
		GPIOA_ODR |= 1<<13;
		for(int i=0;i<5000;i++);
		GPIOA_ODR &=  ~(1<<13);
		for(int i=0;i<5000;i++);
	}

}
